branches:
  only:
  - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  target-branch: gh-pages
  verbose: true
  on:
    branch: master
  # provider: releases
  # api_key: $GITHUB_TOKEN
  # file: dist/*
  # skip_cleanup: true
  # on:
  #   tags: false

after_deploy:
  - node ./scripts/release.js $GITHUB_TOKEN